corrected build.yml and  added coverage file to gitignore

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,4 +1,4 @@
-name: Build on
+name: Sparta sonarCloud scan
 on:
   push:
     branches:
@@ -15,22 +15,22 @@ jobs:
         with:
           fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
           
-      - name: Setup Node.js
-        uses: actions/setup-node@v4
-        with:
-          node-version: '18'
+      # - name: Setup Node.js
+      #   uses: actions/setup-node@v4
+      #   with:
+      #     node-version: '18'
           
       - name: Navigate to front-end directory and install dependencies
         run: |
           cd front-end
           npm install
-          npm install --save-dev @vitest/coverage-v8 @testing-library/react @testing-library/jest-dom
+      # npm install --save-dev @vitest/coverage-v8 @testing-library/react @testing-library/jest-dom
         
       - name: Run unit tests with coverage
         run: |
           cd front-end
-          npm run test:coverage || echo "Tests failed, continuing with SonarQube scan"
-        continue-on-error: true
+          npm run test:coverage || echo "Tests failed"
+        continue-on-error: false
         
       - name: SonarQube Scan
         uses: SonarSource/sonarqube-scan-action@v5
